{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.webgpu",
    "module": "webgpu",
    "version": "1.0.0-dev05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.0",
      "buildId:": "0"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webgpu-1.0.0-dev05-sources.jar",
          "url": "webgpu-1.0.0-dev05-sources.jar",
          "size": 237468,
          "sha512": "43a3fc832159334912674f8d426a27990ff71960693643bc938b316d05b48a5b6c99953235c9f9c1018d054d4451d062d9ea0f3c5bc5eb04fccf4291030faf24",
          "sha256": "a80ab77568a2a0e8c30fd44adb4335105baccabaa6680f0dc1101d110f286e99",
          "sha1": "04d6f58f82b52f5f2085e025d83485bb8ca90497",
          "md5": "288573827f43ad58910c0e304bb0d5e7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "webgpu-1.0.0-dev05.aar",
          "url": "webgpu-1.0.0-dev05.aar",
          "size": 15951077,
          "sha512": "5d39e82b66d1e1772fb8d72c3ba58cbb9a8f14688003e7b4e3120ddd883d28b820ec9ba6ed1cde38f4294691bfe61ae3ef279ac51271466018a9dd95a7a15b65",
          "sha256": "225760545b224a136f28af271ce3e6930119b3619b740b87d771335dfba60f14",
          "sha1": "f6d8b7cf231ed0e9df734bc84b4a024640bbb4bd",
          "md5": "7078422f6e777b02ece889fcf774bac0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "webgpu-1.0.0-dev05.aar",
          "url": "webgpu-1.0.0-dev05.aar",
          "size": 15951077,
          "sha512": "5d39e82b66d1e1772fb8d72c3ba58cbb9a8f14688003e7b4e3120ddd883d28b820ec9ba6ed1cde38f4294691bfe61ae3ef279ac51271466018a9dd95a7a15b65",
          "sha256": "225760545b224a136f28af271ce3e6930119b3619b740b87d771335dfba60f14",
          "sha1": "f6d8b7cf231ed0e9df734bc84b4a024640bbb4bd",
          "md5": "7078422f6e777b02ece889fcf774bac0"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "webgpu-1.0.0-dev05-versionMetadata.json",
          "url": "webgpu-1.0.0-dev05-versionMetadata.json",
          "size": 188122,
          "sha512": "40b538b5211b95093694a434513b9d769cc45d0325503ae6b95fde1c087ea2cf9a575744b8bb592f4cd70661f96f8089f6afa3ba31be07e119bb2e786b5cf7f9",
          "sha256": "196de0dae2ce1f006fd074e2fe4a2e1e3164998f71db7e852bef4c28b00ddc7d",
          "sha1": "77a28812587bc1055f86ed9144cff52bd79f3a2a",
          "md5": "834342a8b6b82d9122ff9c3068967b88"
        }
      ]
    }
  ]
}